In [2]:
import numpy as np
import matplotlib.pyplot as plt 
from tensorflow.keras.models import load_model
import tensorflow as tf

In [16]:
a = np.random.rand(10, 5)
a

array([[0.93955172, 0.4031589 , 0.57295663, 0.84276052, 0.19432551],
       [0.16304617, 0.10473115, 0.51156496, 0.34231534, 0.5358423 ],
       [0.75921663, 0.53074215, 0.50795691, 0.94189619, 0.67734931],
       [0.28466914, 0.273428  , 0.42070199, 0.31241544, 0.35004258],
       [0.5548748 , 0.91010418, 0.23377116, 0.69619461, 0.91498001],
       [0.70583738, 0.76509198, 0.78863886, 0.8974992 , 0.81361337],
       [0.75938893, 0.21352294, 0.51463084, 0.96512648, 0.58484229],
       [0.39877024, 0.2524426 , 0.48590454, 0.10296694, 0.6462742 ],
       [0.7507506 , 0.32528288, 0.66503956, 0.13019906, 0.33479805],
       [0.26515066, 0.37056651, 0.14347594, 0.14130264, 0.67504609]])

In [20]:
a_row = a[0, :]
a_row = np.reshape(a_row, (1, 5))

In [21]:
at = tf.constant(a_row)
at

<tf.Tensor: shape=(1, 5), dtype=float64, numpy=array([[0.93955172, 0.4031589 , 0.57295663, 0.84276052, 0.19432551]])>

In [26]:
bt = at[:, :4]
bt

<tf.Tensor: shape=(1, 4), dtype=float64, numpy=array([[0.93955172, 0.4031589 , 0.57295663, 0.84276052]])>

In [31]:
xt = at[:, :3]
xt


<tf.Tensor: shape=(1, 3), dtype=float64, numpy=array([[0.93955172, 0.4031589 , 0.57295663]])>

In [34]:
yt = at[:, 4]
yt = tf.reshape(yt, [1,1])

In [35]:
tf.concat([xt, yt], 1)

<tf.Tensor: shape=(1, 4), dtype=float64, numpy=array([[0.93955172, 0.4031589 , 0.57295663, 0.19432551]])>

In [41]:
model = load_model("./models/model_two_l50_j5_n5000_r0/")

In [42]:
bm1 = [[0.1953125,  0.390625,   0.5859375,  0. ,        0.390625,   0.1953125,
  0.1953125,  0.5859375,  0.5859375,  0.1953125,  0.390625,   0.1953125,
  0.390625,   0.1953125,  0.1953125,  0.390625,   0.1953125,  0.,
  0.390625,   0.1953125,  0.390625,   0.390625,   0.5859375,  0.,
  0.390625,   0.1953125,  0.78125,    0.390625,   0.5859375,  0.,
  0.390625,   0.390625,   0.,         0.390625,   0.1953125,  0.,
  0.1953125,  0.1953125,  0.,         0.1953125,  0.390625,   0.,
  0.5859375,  0.,         0.1953125,  0.,         0.1953125,  0.1953125,
  0.1953125,  0.,        0.50212502, 0.47221244]]

In [43]:
model.predict(bm1)

1/1 [==============================] - 0s 182ms/step


array([[0.3901256]], dtype=float32)